//	This file was created on Fri Feb 07 16:01:01 EST 2020 by user 'plastic'
//	*** this file is automatically generated.  Do not edit.
CREATE CONSTRAINT ON (n:Cell) ASSERT n.id IS UNIQUE;
CREATE INDEX ON :Cell(cell_histology);
CREATE CONSTRAINT ON (n:Gene) ASSERT n.pr_gene_symbol IS UNIQUE;
CREATE INDEX ON :Gene(pr_gene_title);
CREATE INDEX ON :Gene(description);
CREATE INDEX ON :Gene(idg2);
CREATE INDEX ON :Gene(tdl);
CREATE INDEX ON :Gene(fam);
CREATE INDEX ON :Gene(uniprot);
CREATE CONSTRAINT ON (n:Drug) ASSERT n.id IS UNIQUE;
CREATE INDEX ON :Drug(pert_iname);
CREATE INDEX ON :Drug(pert_type);
CREATE CONSTRAINT ON (n:Signature) ASSERT n.id IS UNIQUE;
CREATE INDEX ON :Signature(cell_id);
CREATE INDEX ON :Signature(pert_id);
CREATE INDEX ON :Signature(pert_type);
CREATE INDEX ON :Signature(pert_idose);
CREATE INDEX ON :Signature(pert_iname);
