#!/bin/bash
echo "wait for neo4j bolt to respond at port $1"

CONTAINER=$1
PORT=$2

if [ -z ${CONTAINER} ] || [ -z ${PORT} ]
  then
     echo "Usage:"
     echo "  wait4bolt_outside docker_container port"
     echo "  e.g. wait4bolt_outside neo_ag 7687"
     exit 1
fi

# this returns before server is ready
#    curl -i http://127.0.0.1:${PORT} 2>&1 | grep -c -e '200 OK' || break 

# try an actual query as test?
docker exec -t \
  --env NEO4J_USERNAME=${NEO4J_USERNAME} \
  --env NEO4J_PASSWORD=${NEO4J_PASSWORD} \
  ${CONTAINER} \
  bash -c "until echo 'match (n) return count(n);' | bin/cypher-shell -a bolt://localhost:${PORT}; do echo $? ; sleep 1; done"

retVal=$?
if [ $retVal -ne 0 ]; then
    echo "Error neo4j NOT online"
else
    echo "neo4j online!"
fi
exit $retVal

